### ISSUE TITLE
Questions about the thermophysical transport coefficients?

### ISSUE THREAD

**Issue by scramjetFoam** [yuchenzh/DDOF#1]
Hi,

In Cantera, there are binary_diff_coeffs, mix_diff_coeffs, multi_diff_coeffs. Is multi_diff_coeffs better for using the FickianFourier and MaxwellStefanFourier thermophysical transport models in OpenFOAM that take into account the Soret effect?

BR,
Shang

**Comment by yuchenzh** [comment]
Hi,

The soret effect should be able to be included in my implementation, suggested by https://cpp.openfoam.org/v10/FickianFourier_8H_source.html (please check the header). I have never tested that before.
         DT // [kg/m/s] Optional
         {
             O2 1e-2;
             O3 5e-2;
             N2 1e-2;
         }

It might not be relevant to those different coefficients you suggests.
mix_diff_coeffs is obtained from the mixture-averaged model, which corresponds to Fickian in OpenFOAM.
mult_diff_coeffs might be another model (multi-component transport), I am not sure whether it is stefan-maxwell.

This implementation has not been tested enough with DNS. Do you have any testing results for H2 flame speed?
You might add my wechat (Chris_Mcfly), or send me an email:yuchen.zhou@energy.lth.se. I am curious to know that.

Best regards,
Yuchen

**Comment by scramjetFoam** [comment]
> Hi,
> 
> The soret effect should be able to be included in my implementation, suggested by https://cpp.openfoam.org/v10/FickianFourier_8H_source.html (please check the header). I have never tested that before. DT // [kg/m/s] Optional { O2 1e-2; O3 5e-2; N2 1e-2; }
> 
> It might not be relevant to those different coefficients you suggests. mix_diff_coeffs is obtained from the mixture-averaged model, which corresponds to Fickian in OpenFOAM. mult_diff_coeffs might be another model (multi-component transport), I am not sure whether it is stefan-maxwell.
> 
> This implementation has not been tested enough with DNS. Do you have any testing results for H2 flame speed? You might add my wechat (Chris_Mcfly), or send me an email:[yuchen.zhou@energy.lth.se](mailto:yuchen.zhou@energy.lth.se). I am curious to know that.
> 
> Best regards, Yuchen

Hi,

You are right about the different coefficients, I also realized this problem and chose to close it. In my earlier test, the laminar flame did not reach steady state so the calculations were way off, I fixed this later and the results fit well. I will add your WeChat. 

![flame_speed_vs_phi](https://github.com/yuchenzh/DDOF/assets/80505084/b1832f07-3062-495e-b9a9-872bb1fc5e5f)

Regards,
Shang
